//! PyTorch-aligned *frontend recognition* catalog for NN-01..NN-34.
//!
//! Names are ordinary J NAMEs resolved after user bindings. This catalog is
//! not an executable registry, a Graph atom, a J error-order witness, or proof
//! that PyTorch tensor broadcasting agrees with J Rank/fill semantics.
use crate::primitive::{
    ExtensionPrimitive, LoweringKey, PrimitiveContext, PrimitiveHandle, PrimitivePartOfSpeech,
    PrimitiveResolver, PrimitiveSemanticId, PrimitiveSemanticInfo, PrimitiveSourceOrigin,
    REGISTRY_VERSION,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ShapeRule {
    Preserve,
    Flatten,
    Reduction,
    Contraction,
    Window,
    Normalize,
    Index,
    Selection,
    Stateful,
    NeedsDefinition,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DTypeRule {
    Preserve,
    Floating,
    Promote,
    IndexInteger,
    NeedsDefinition,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EffectRule {
    PureCandidate,
    ExplicitState,
    ExplicitStateWhenTraining,
    ExplicitRng,
    Registration,
    Unresolved,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RouteCandidate {
    Elementwise,
    Reindex,
    Reduce,
    Contract,
    Window,
    Gather,
    Scatter,
    Scan,
    Composite,
    NoExecutableRoute,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProofStatus {
    Unverified,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct NnFamilySpec {
    pub id: &'static str,
    pub parameter_schema: &'static str,
    pub shape_rule: ShapeRule,
    pub dtype_rule: DTypeRule,
    pub effect_rule: EffectRule,
    pub logical_route_candidate: RouteCandidate,
    pub empty_fill_proof: ProofStatus,
    pub error_order_proof: ProofStatus,
    pub numeric_proof: ProofStatus,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct NnExtensionName {
    pub family_id: &'static str,
    pub spelling: &'static str,
    pub semantic_identity: &'static str,
    /// None: no matching stable public PyTorch/Torchvision leaf API is claimed.
    pub pytorch_api: Option<&'static str>,
    pub pos: PrimitivePartOfSpeech,
    /// J intrinsic (monad, dyad-left, dyad-right); 63 = unbounded cell rank.
    pub intrinsic_ranks: Option<[i64; 3]>,
    /// Rank on the constructed verb, not on the adverb/conjunction builder.
    pub derived_verb_ranks: Option<[i64; 3]>,
    /// Separate opt-in frontend E2E profile, no runtime/backend support.
    pub frontend_preview: bool,
}

macro_rules! nn {
    ($family:expr, $name:literal, $api:expr, $pos:ident,
     $intrinsic:expr, $derived:expr, $preview:expr $(,)?) => {
        NnExtensionName {
            family_id: $family,
            spelling: $name,
            semantic_identity: concat!("nn.", $name),
            pytorch_api: $api,
            pos: PrimitivePartOfSpeech::$pos,
            intrinsic_ranks: $intrinsic,
            derived_verb_ranks: $derived,
            frontend_preview: $preview,
        }
    };
}

/// 34 family contracts; the only *completion* checklist is PROJECT.ko.md §4.6.
pub const FAMILIES: &[NnFamilySpec] = &[
    NnFamilySpec {
        id: "NN-01",
        parameter_schema: "input; inplace forbidden",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::Preserve,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Elementwise,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-02",
        parameter_schema: "input, weight, bias",
        shape_rule: ShapeRule::Contraction,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Contract,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-03",
        parameter_schema: "input, start_dim=0, end_dim=-1",
        shape_rule: ShapeRule::Flatten,
        dtype_rule: DTypeRule::Preserve,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Reindex,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-04",
        parameter_schema: "input, weight, bias, stride, padding, dilation, groups",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Window,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-05",
        parameter_schema: "input, kernel_size, stride, padding, ceil_mode, indices/count_include_pad",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Window,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-06",
        parameter_schema: "input, dim, dtype",
        shape_rule: ShapeRule::Normalize,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Reduce,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-07",
        parameter_schema: "input, target, weight, ignore_index, reduction, label_smoothing",
        shape_rule: ShapeRule::Reduction,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-08",
        parameter_schema: "input, weight, bias, stride, padding, dilation, groups",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Window,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-09",
        parameter_schema: "input, normalization axes, affine, eps, running statistics",
        shape_rule: ShapeRule::Normalize,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::ExplicitStateWhenTraining,
        logical_route_candidate: RouteCandidate::Reduce,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-10",
        parameter_schema: "input; approximate mode must be explicit",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Elementwise,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-11",
        parameter_schema: "indices, weight, padding_idx, max_norm, scale_grad_by_freq",
        shape_rule: ShapeRule::Index,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Gather,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-12",
        parameter_schema: "query, key, value, mask, dropout_p, causal, scale, enable_gqa",
        shape_rule: ShapeRule::Contraction,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::Unresolved,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-13",
        parameter_schema: "position, frequencies, rotation dimension",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-14",
        parameter_schema: "input, other; existing-J contraction recognition",
        shape_rule: ShapeRule::Contraction,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Contract,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-15",
        parameter_schema: "input, p, training, explicit generator/key",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::Preserve,
        effect_rule: EffectRule::ExplicitRng,
        logical_route_candidate: RouteCandidate::Elementwise,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-16",
        parameter_schema: "function, primals, cotangent, input-specific VJP",
        shape_rule: ShapeRule::NeedsDefinition,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::Unresolved,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-17",
        parameter_schema: "parameters, gradients, moment, step, explicit StateResource",
        shape_rule: ShapeRule::Stateful,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::ExplicitState,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-18",
        parameter_schema: "registered forward, VJP rules, residuals",
        shape_rule: ShapeRule::NeedsDefinition,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::Registration,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-19",
        parameter_schema: "input, dtype, rounding/overflow, residual requirements",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::Unresolved,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-20",
        parameter_schema: "input, weight/output_size, padding, stride, groups",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Window,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-21",
        parameter_schema: "input, scale, zero_point, dtype, saturation",
        shape_rule: ShapeRule::Preserve,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::Unresolved,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-22",
        parameter_schema: "cache StateResource, index, value, version",
        shape_rule: ShapeRule::Stateful,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::ExplicitState,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-23",
        parameter_schema: "grouped inputs, routing/offsets, expert weights",
        shape_rule: ShapeRule::Contraction,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Contract,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-24",
        parameter_schema: "input, dim, keepdim; stable logsumexp",
        shape_rule: ShapeRule::Reduction,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Reduce,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-25",
        parameter_schema: "input, k, dim, largest, sorted; values+indices",
        shape_rule: ShapeRule::Selection,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-26",
        parameter_schema: "input, num_groups, affine, eps; running-stat distinction",
        shape_rule: ShapeRule::Normalize,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::ExplicitStateWhenTraining,
        logical_route_candidate: RouteCandidate::Reduce,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-27",
        parameter_schema: "data, segment lengths/offsets, reduction, embedding weights",
        shape_rule: ShapeRule::Reduction,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-28",
        parameter_schema: "input, dim, index, src, reduce, include_self; collision order",
        shape_rule: ShapeRule::Index,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Scatter,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-29",
        parameter_schema: "input, grid or target size; mode, align_corners, padding",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Promote,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Gather,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-30",
        parameter_schema: "size/probabilities, explicit key or generator, dtype",
        shape_rule: ShapeRule::Stateful,
        dtype_rule: DTypeRule::NeedsDefinition,
        effect_rule: EffectRule::ExplicitRng,
        logical_route_candidate: RouteCandidate::NoExecutableRoute,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-31",
        parameter_schema: "input, hidden/cell state, weights, lengths, direction",
        shape_rule: ShapeRule::Stateful,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::ExplicitState,
        logical_route_candidate: RouteCandidate::Scan,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-32",
        parameter_schema: "boxes, scores, iou_threshold; tie order",
        shape_rule: ShapeRule::Selection,
        dtype_rule: DTypeRule::IndexInteger,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Composite,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-33",
        parameter_schema: "input, boxes, output_size, spatial_scale, sampling_ratio",
        shape_rule: ShapeRule::Window,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Window,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
    NnFamilySpec {
        id: "NN-34",
        parameter_schema: "log_probs, targets, input_lengths, target_lengths, blank, reduction",
        shape_rule: ShapeRule::Reduction,
        dtype_rule: DTypeRule::Floating,
        effect_rule: EffectRule::PureCandidate,
        logical_route_candidate: RouteCandidate::Scan,
        empty_fill_proof: ProofStatus::Unverified,
        error_order_proof: ProofStatus::Unverified,
        numeric_proof: ProofStatus::Unverified,
    },
];

/// PyTorch-aligned spellings; speculative/nonstandard names remain hidden
/// from the frontend preview, and all names remain non-executable.
pub const NAMES: &[NnExtensionName] = &[
    nn!(
        "NN-01",
        "relu",
        Some("torch.nn.functional.relu"),
        Verb,
        Some([0; 3]),
        None,
        true
    ),
    nn!(
        "NN-01",
        "sigmoid",
        Some("torch.nn.functional.sigmoid"),
        Verb,
        Some([0; 3]),
        None,
        true
    ),
    nn!(
        "NN-01",
        "tanh",
        Some("torch.nn.functional.tanh"),
        Verb,
        Some([0; 3]),
        None,
        true
    ),
    nn!(
        "NN-02",
        "linear",
        Some("torch.nn.functional.linear"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-03",
        "flatten",
        Some("torch.flatten"),
        Verb,
        Some([63; 3]),
        None,
        true
    ),
    nn!(
        "NN-04",
        "conv2d",
        Some("torch.nn.functional.conv2d"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-05",
        "avg_pool2d",
        Some("torch.nn.functional.avg_pool2d"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-05",
        "max_pool2d",
        Some("torch.nn.functional.max_pool2d"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-06",
        "softmax",
        Some("torch.nn.functional.softmax"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-06",
        "log_softmax",
        Some("torch.nn.functional.log_softmax"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-07",
        "cross_entropy",
        Some("torch.nn.functional.cross_entropy"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-08",
        "conv1d",
        Some("torch.nn.functional.conv1d"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-08",
        "conv3d",
        Some("torch.nn.functional.conv3d"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-09",
        "layer_norm",
        Some("torch.nn.functional.layer_norm"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-09",
        "rms_norm",
        Some("torch.nn.functional.rms_norm"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-09",
        "batch_norm",
        Some("torch.nn.functional.batch_norm"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-10",
        "gelu",
        Some("torch.nn.functional.gelu"),
        Verb,
        Some([0; 3]),
        None,
        true
    ),
    nn!(
        "NN-10",
        "silu",
        Some("torch.nn.functional.silu"),
        Verb,
        Some([0; 3]),
        None,
        true
    ),
    nn!(
        "NN-11",
        "embedding",
        Some("torch.nn.functional.embedding"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-12",
        "scaled_dot_product_attention",
        Some("torch.nn.functional.scaled_dot_product_attention"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-13",
        "rotary_embedding",
        None,
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-14",
        "matmul",
        Some("torch.matmul"),
        Verb,
        Some([63; 3]),
        None,
        true
    ),
    nn!(
        "NN-15",
        "dropout",
        Some("torch.nn.functional.dropout"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-16",
        "vjp",
        Some("torch.func.vjp"),
        Adverb,
        None,
        None,
        false
    ),
    nn!(
        "NN-17",
        "SGD",
        Some("torch.optim.SGD"),
        Adverb,
        None,
        None,
        false
    ),
    nn!(
        "NN-17",
        "Adam",
        Some("torch.optim.Adam"),
        Adverb,
        None,
        None,
        false
    ),
    nn!(
        "NN-17",
        "AdamW",
        Some("torch.optim.AdamW"),
        Adverb,
        None,
        None,
        false
    ),
    nn!(
        "NN-18",
        "register_autograd",
        Some("torch.library.register_autograd"),
        Conjunction,
        None,
        None,
        false,
    ),
    nn!(
        "NN-19",
        "to",
        Some("torch.Tensor.to"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-20",
        "conv_transpose2d",
        Some("torch.nn.functional.conv_transpose2d"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-20",
        "adaptive_avg_pool2d",
        Some("torch.nn.functional.adaptive_avg_pool2d"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-20",
        "adaptive_max_pool2d",
        Some("torch.nn.functional.adaptive_max_pool2d"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-21",
        "quantize_per_tensor",
        Some("torch.quantize_per_tensor"),
        Adverb,
        None,
        Some([63; 3]),
        false,
    ),
    nn!(
        "NN-21",
        "dequantize",
        Some("torch.Tensor.dequantize"),
        Verb,
        Some([63; 3]),
        None,
        false
    ),
    nn!("NN-22", "kv_cache_update", None, Adverb, None, None, false),
    nn!(
        "NN-23",
        "grouped_mm",
        Some("torch.nn.functional.grouped_mm"),
        Adverb,
        None,
        Some([63; 3]),
        false,
    ),
    nn!(
        "NN-24",
        "logsumexp",
        Some("torch.logsumexp"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-25",
        "topk",
        Some("torch.topk"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-26",
        "group_norm",
        Some("torch.nn.functional.group_norm"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-26",
        "instance_norm",
        Some("torch.nn.functional.instance_norm"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-27",
        "segment_reduce",
        Some("torch.segment_reduce"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-27",
        "embedding_bag",
        Some("torch.nn.functional.embedding_bag"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-28",
        "scatter_reduce",
        Some("torch.scatter_reduce"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-28",
        "index_add",
        Some("torch.index_add"),
        Adverb,
        None,
        Some([63; 3]),
        true
    ),
    nn!(
        "NN-29",
        "interpolate",
        Some("torch.nn.functional.interpolate"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-29",
        "grid_sample",
        Some("torch.nn.functional.grid_sample"),
        Adverb,
        None,
        Some([63; 3]),
        true,
    ),
    nn!(
        "NN-30",
        "rand",
        Some("torch.rand"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-30",
        "randn",
        Some("torch.randn"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-30",
        "bernoulli",
        Some("torch.bernoulli"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-30",
        "multinomial",
        Some("torch.multinomial"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-31",
        "RNN",
        Some("torch.nn.RNN"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-31",
        "GRU",
        Some("torch.nn.GRU"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-31",
        "LSTM",
        Some("torch.nn.LSTM"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-32",
        "nms",
        Some("torchvision.ops.nms"),
        Adverb,
        None,
        Some([63; 3]),
        false
    ),
    nn!(
        "NN-33",
        "roi_align",
        Some("torchvision.ops.roi_align"),
        Adverb,
        None,
        Some([63; 3]),
        false,
    ),
    nn!(
        "NN-34",
        "ctc_loss",
        Some("torch.nn.functional.ctc_loss"),
        Adverb,
        None,
        Some([63; 3]),
        false,
    ),
];

pub fn family(id: &str) -> Option<&'static NnFamilySpec> {
    FAMILIES.iter().find(|spec| spec.id == id)
}

/// Preview recognition only. Does not change Engine::new() or J built-ins.
pub fn frontend_preview_context() -> PrimitiveContext {
    let extensions = NAMES
        .iter()
        .filter(|spec| spec.frontend_preview)
        .map(|spec| ExtensionPrimitive {
            spelling: spec.spelling,
            handle: PrimitiveHandle {
                semantic_id: PrimitiveSemanticId::Extension(spec.semantic_identity),
                source_origin: PrimitiveSourceOrigin::Extension,
                result_pos: spec.pos,
                semantic_info: PrimitiveSemanticInfo {
                    registry_version: REGISTRY_VERSION,
                },
                lowering_key: LoweringKey::Extension(spec.semantic_identity),
            },
        });
    PrimitiveContext::new(
        PrimitiveResolver::with_extensions(extensions)
            .expect("checked static NN frontend-only catalog"),
    )
}
